# Fichero de configuraci贸n para los contenedores del cliente de la aplicaci贸n CarShare
version: "3.8"
services:
  # Crea un contenedor con la api de la aplicaci贸n
  horario:
    # La imagen del contenedor se construye sobre una adecuando las necesidades
    build: .
    # Nombre asignado al contenedor
    container_name: horario
    # Para la versi贸n de desarrollo se mapea la carpeta con una local
    ports: 
      - 1001:4200
    volumes:
      - .:/usr/src/app
    networks:
      - horario
networks:
    horario:
        driver: bridge
